### ISSUE TITLE
absolute noob question

### ISSUE THREAD

**Issue by hotpotatodude** [walczakp/xbox360-rpi-flasher#12]
how do you compile this sorry for bothering you i wanna try this on my raspberry pi zero w cause picos are quite expensive where i live

**Comment by walczakp** [comment]
I don't really remember which packages you'd need on Raspbian or whatever people install on Pis these days. Definitely `sudo apt-get install build-essential` is a must, then you can try to run `make` and see if it compiles.

That being said, I couldn't make it to work on Zero W, it's too slow and such precise bit banging requires no operating system interference. It will simply not work.

**Comment by hotpotatodude** [comment]
thanks :D also thats a bummer thats zero ws dont work

**Comment by hotpotatodude** [comment]
hey sorry for talking in this completed issue i tried making it with the instructions you said and it gave me this error
gcc -c -o obj/main.o main.c -Wall -g -I/home/joaop/xbox360-rpi-flasher
main.c:6:10: fatal error: wiringPi.h: No such file or directory
    6 | #include <wiringPi.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:18: obj/main.o] Error 1

**Comment by hotpotatodude** [comment]
nvm had to install WiringPi i did it sorry
