### ISSUE TITLE
Can this write to the xbox also?

### ISSUE THREAD

**Issue by ahpook** [walczakp/xbox360-rpi-flasher#3]
Hi, very cool project - I see there are routines for writing in XNAND.c but there doesn't appear to be a way to use them. Am i missing something?

**Comment by walczakp** [comment]
Hello. Unfortunately, I have only RPi Zero W to test on, which is unreliable even with reads. There are routines for writing, but I never wrote code to use them.

I had more luck with Teensy board: https://github.com/walczakp/xbox360-teensy-flasher

**Comment by walczakp** [comment]
FWIW, @mav2010 just added a way to use write routines on RPi 4 as well.
