### ISSUE TITLE
Does not work on pi 2 and corona 16mb

### ISSUE THREAD

**Issue by Khysnik** [walczakp/xbox360-rpi-flasher#8]
Nand dumps are bad. 
![image](https://github.com/walczakp/xbox360-rpi-flasher/assets/57809907/17d4a7f9-b910-428a-a25d-775ecd022082)

**Comment by Ancient123** [comment]
As the person that got this working with a Pi4 consistently for the first time. I *highly* recommend people getting a Pi Pico and using https://github.com/X360Tools/PicoFlasher .

Running a full operating system makes this kind of super sensitive IO via GPIO pins very inconsistent.

**Comment by walczakp** [comment]
Indeed, that's my recommendation as well.

wt., 13 cze 2023, 17:28 użytkownik Mat R. ***@***.***>
napisał:
